query GetUpcomingEvent($where: ArtistWhereInput!) {
  artist(where: $where) {
    events(take: 1, orderBy: { date: desc }) {
      id
      name
      date
      url
      description
      venue {
        name
        address
        city
        state
        zip
      }
    }
  }
}
